import = [
    "~/.config/alacritty/local-themes/tokyonight-day.toml",
    "~/.config/alacritty/local-themes/spacemacs-light.toml",
    "~/.config/alacritty/themes/themes/one_dark.toml",
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml",
    "~/.config/alacritty/themes/themes/doom_one.toml",
]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Transparent"
# decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 16.0

[cursor]
style = { shape = "Block" }

[env]
MACOS_TERM_PROGRAM = "alacritty"

[keyboard]
bindings = [
{ key = "G", mods = "Command", mode = "Search", action = "SearchFocusNext" },
{ key = "G", mods = "Shift|Command", mode = "Search", action = "SearchFocusPrevious" },
{ key = "PageUp", action = "ScrollPageUp" },
{ key = "PageDown", action = "ScrollPageDown" }
]
