# Spacemacs light Alacritty Colors
[colors.primary]
background = '#fbf8ef'
foreground = '#655370'

[colors.cursor]
cursor = '#da8b55'
text = '#e1e2e7'

[colors.selection]
text = "#655370"
background = "#d2ceda"

[colors.normal]
black = '#100a14'
red = '#ba2f59'
green = '#2d9574'
yellow = '#b1951d'
blue = '#3a81c3'
magenta = '#a31db1'
cyan = '#2aa1ae'
white = '#efeae9'

[colors.bright]
black = '#a8a8bf'
red = '#e0211d'
green = '#67b11d'
yellow = '#da8b55'
blue = '#3a81c3'
magenta = '#9380b2'
cyan = '#21b8c7'
white = '#f6f1e1'
